<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GraduationDegree;

class GraduationCourse extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' =>'B.Tech. (Bachelor of Technology) - Computer Science Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Mechanical Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Electrical Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Electronics and Communication and Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Civil Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Chemical Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Aerospace Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Biotechnology Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Environmental Engineering'],
            ['name' =>'B.Tech. (Bachelor of Technology) - Artificial Intelligence and Machine Learning'],
            ['name' =>'B.E (Bachelor of Engineering) - Computer Science Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Mechanical Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Electrical Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Electronics and Communication and Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Civil Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Chemical Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Aerospace Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Biotechnology Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Environmental Engineering'],
            ['name' =>'B.E (Bachelor of Engineering) - Artificial Intelligence and Machine Learning'],
            ['name' =>'B.Sc. (Bachelor of Science) - Mathematics'],
            ['name' =>'B.Sc. (Bachelor of Science) - Physics'],
            ['name' =>'B.Sc. (Bachelor of Science) - Chemistry'],
            ['name' =>'B.Sc. (Bachelor of Science) - Biology'],
            ['name' =>'B.Sc. (Bachelor of Science) - Computer Science'],
            ['name' =>'B.Sc. (Bachelor of Science) - Electronics'],
            ['name' =>'B.Sc. (Bachelor of Science) - Biotechnology'],
            ['name' =>'B.Sc. (Bachelor of Science) - Agriculture'],
            ['name' =>'B.Sc (Bachelort of Science) - Nursing'],
            ['name' =>'B.Sc (Bachelort of Science) - Trauma Care Management'],
            ['name' =>'B.FTech. (Bachelor of Fashion Technology) - Apparel Production'],
            ['name' =>'B.FTech. (Bachelor of Fashion Technology) - Fashion Design'],
            ['name' =>'B.FTech. (Bachelor of Fashion Technology) - Textile Design'],
            ['name' =>'B.FTech. (Bachelor of Fashion Technology) - Leather Design'],
            ['name' =>'B.FTech. (Bachelor of Fashion Technology) - Knitwear Desig'],
            ['name' =>'B. Arch. (Bachelor of Architecture) - Architecture'],
            ['name' =>'B. Arch. (Bachelor of Architecture) - Interior Design'],
            ['name' =>'B. Arch. (Bachelor of Architecture) - Landscape Architecture'],
            ['name' =>'B. Arch. (Bachelor of Architecture) - Building Science'],
            ['name' =>'B. Plan. (Bachelor of Planning) - Urban Planning'],
            ['name' =>'B. Plan. (Bachelor of Planning) - Regional Planning'],
            ['name' =>'B. Plan. (Bachelor of Planning) - Environmental Planning'],
            ['name' =>'B. Plan. (Bachelor of Planning) - Transportation Planning'],
            ['name' =>'B. Plan. (Bachelor of Planning) - Infrastructure Planning'],
            ['name' =>'B.I.D (Bachelor of Interior Design) - Initerior Design'],
            ['name' =>'B.I.D (Bachelor of Interior Design) - Furniture Design'],
            ['name' =>'B.I.D (Bachelor of Interior Design) - Spatial Design'],
            ['name' =>'B.I.D (Bachelor of Interior Design) - Exhibition Design'],
            ['name' =>'B. Des. (Bachelor of Design) - Fashion Design'],
            ['name' =>'B. Des. (Bachelor of Design) - Product Design'],
            ['name' =>'B. Des. (Bachelor of Design) - Interior Design'],
            ['name' =>'B. Des. (Bachelor of Design) - Graphic Design'],
            ['name' =>'B. Des. (Bachelor of Design) - Animation Design'],
            ['name' =>'Dual Programs in Engineering (B.Tech. + M.Tech) - Electrical Engineering'],
            ['name' =>'Dual Programs in Engineering (B.Tech. + M.Tech) - Computer Science Engineering'],
            ['name' =>'Dual Programs in Engineering (B.Tech. + M.Tech) - Mechanical Engineering'],
            ['name' =>'Dual Programs in Engineering (B.Tech. + M.Tech) - Civil Engineering'],
            ['name' =>'B.Com. (Bachelor of Commerce) - Accounting and Finance'],
            ['name' =>'B.Com. (Bachelor of Commerce) - Banking and Insurance'],
            ['name' =>'B.Com. (Bachelor of Commerce) - Taxation'],
            ['name' =>'B.Com. (Bachelor of Commerce) - Computer Applications'],
            ['name' =>'B.Com. (Bachelor of Commerce) - E-Commerce'],
            ['name' =>'B.Com. (Hons.) (Bachelor of Commerce Honos.) - Accounting and Finance'],
            ['name' =>'B.Com. (Hons.) (Bachelor of Commerce Honos.) - Banking and Insurance'],
            ['name' =>'B.Com. (Hons.) (Bachelor of Commerce Honos.) - Taxation'],
            ['name' =>'B.Com. (Hons.) (Bachelor of Commerce Honos.) - Marketing'],
            ['name' =>'B.Com. (Hons.) (Bachelor of Commerce Honos.) - Human Resource Management'],
            ['name' =>'B.D.S (Bachelor of Dental Surgery) - Dental Surgery'],
            ['name' =>'B.A.M.S (Bachelor of Ayurvedic Medicine & Surgery) - Aryudedic Medicine & Surger'],
            ['name' =>'B.S.M.S (Bachelor of Siddha Medicine & Surgery) - Siddha Medicine & Surgery'],
            ['name' =>'B.N.Y.S (Bachelor of Naturopathy & Yogic Science) - Naturopathy & Yogic Science'],
            ['name' =>'B.H.M.S (Bachelor of Homeopathic Medicine & Surgery) - Homeopathic Medicine & Surgery'],
            ['name' =>'B.U.M.S (Bachelor of Unani Medicine & Surgery) - Unani Medicine & Surgery'],
            ['name' =>'B.Optom. (Bachelor of Optometry) - Optometry'],
            ['name' =>'B.O.T (Bachelor of Occupational Therapy) - Occupational Therapy'],
            ['name' =>'B.P.T (Bachelor of Physiotherapy) - Physiotherapy'],
            ['name' =>'D. Pharma (Doctor of Pharmacy) - Pharmacy'],
            ['name' =>'B. Pharma (Bachelor of Pharmacy) - Pharmacy'],
            ['name' =>'B. Pharm (Ayu) (Bachelor of Pharmacy (Aryuveda)) - Pharmacy (Aryuveda)'],
            ['name' =>'B.P.O. (Bachelor of Prosthetics & Orthotics) - Prosthetics & Orthotics'],
            ['name' =>'B. ASLP (Bachelor in Audiology & Speech Language Pathology) - Audiology & Speech Language Pathology'],
            ['name' =>'B.R. Sc. (Bachelor in Rehabilitation Science) - Rehabilitation Science'],
            ['name' =>'B.V. Sc. (Bachelor of Veterinary Sciences) - Veterinary Sciences'],
            ['name' =>'B.F. Sc. (Bachelor of Fisheries Science) - Fisheries Science'],
            ['name' =>'B.Sc. (Bachelor of Science) - Finance'],
            ['name' =>'B.Sc. (Bachelor of Science) - Hospitality & Hotel Administration'],
            ['name' =>'B.Sc. Hons. (Bachelor of Science) - Economics'],
            ['name' =>'B.B.A (Bachelor of Business Administration) - Finance'],
            ['name' =>'B.F.A (Bachelor of Financial Accounting) - Financial Accounting'],
            ['name' =>'B.Com. (Bachelor of Commerce) - Professional'],
            ['name' =>'B.A (Bachelor in Arts) - English, History, Political Science, Socialogy, Psychology, Economics, Fine Arts - or Language Hindi, Sanskrit, French, German and Spanish among others'],
            ['name' =>'B.A. (Hons) - Hotel Management'],
            ['name' =>'B.A. (Hons) - Culinary Arts'],
            ['name' =>'B.A (Bachelor in Arts) - Journalism'],
            ['name' =>'B.A (Bachelor in Arts) - Communication Media'],
            ['name' =>'B.A (Bachelor in Arts) - Sports Management'],
            ['name' =>'C.A (Chartered Accountant) - Chartered Accountant'],
            ['name' =>'C.S (Company Secretary) - Company Secretary'],
            ['name' =>'C.W.A (Cost and Works Accountant) - Cost and Works Accountant'],
            ['name' =>'C.F.A (Certified Finance Analyst) - Certified Finance Analyst'],
            ['name' =>'C.F.P (Certified Financial Planner) - Certified Financial Planner'],
            ['name' =>'C.I.B (Certified Investment Banker) - Certified Investment Banker'],
            ['name' =>'C.S.B (Certified Stock Broker) - Certified Stock Broker'],
            ['name' =>'C.I.A (Certified Investment Analyst) - Certified Investment Analyst'],
            ['name' =>'Certified Actuary - Certified Actuary'],
            ['name' =>'NSE Certifications - NSE Certifications'],
            ['name' =>'B.S.E Certifications - B.S.E Certifications'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - General'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - Marketing'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - Finance'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - Human Resources'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - International Business'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - Information Technology'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - Entrepreneurship'],
            ['name' =>'B.B.A (Bachelor in Business Administration) - Operations Management'],
            ['name' =>'B.B.A (Bachelor of Business Administration) - Sports Management'],
            ['name' =>'B.Sc. LLB (Bachelor In Science & Bachelor in Law) - Bachelor in Law'],
            ['name' =>'B.A LLB (Bachelor in Arts & Bachelor in Law) - B.sc with Bachelor in Law'],
            ['name' =>'B.Com LLB (Bachelor in Commerce & Bachelor in Law) - B.Com with Bachelor in Law'],
            ['name' =>'B.B.A LLB (Bachelor in Business Administration & Bachelor in Law) - B.B.A Bachelor in Law'],
            ['name' =>'B.L.S LLB (Bachelor in Liberal Arts & Bachelor in Law) - B.L.S Bachelor in Law'],
            ['name' =>'B.S.W LLB (Bachelor in Social Work & Bachelor in Law) - B.S.W Bachelor in Law'],
            ['name' =>'B. Tech LLB (Bachelor in Technology & Bachelor in Law) - B.Tech with Bachelor in Law'],
            ['name' =>'B.M.S (Bachelor in Management Studies) - Bachelor in Management Studies'],
            ['name' =>'B.B.S (Bachelor in Business Studies) - Bachelor in Business Studies'],
            ['name' =>'B.B.M (Bachelor in Business Management) - Bachelor in Business Management'],
            ['name' =>'B.Tech (Bachelor of Technology) - Hotel Management & Catering Technology'],
            ['name' =>'B.M.M (Bachelor in Mass Media) - Bachelor in Mass Media'],
            ['name' =>'B.M.C (Bachelor in Mass Communication) - Bachelor in Mass Communication'],
            ['name' =>'B.M.S (Bachelor in Media Studies) - Bachelor in Media Studies'],
            ['name' =>'B.J.M.C (Bachelor in Journalism & Mass Communication) - Bachelor in Journalism & Mass Communication'],
            ['name' =>'B.S.W (Bachelor in Social Work) - Bachelor in Social Work'],
            ['name' =>'B.R.S (Bachelor in Rural Studies) - Bachelor in Rural Studies'],
            ['name' =>'B.C.A (Bachelor in Computer Application) - General'],
            ['name' =>'B.C.A (Bachelor in Computer Application) - Database Management'],
            ['name' =>'B.C.A (Bachelor in Computer Application) - Web Development'],
            ['name' =>'B.C.A (Bachelor in Computer Application) - Software Development'],
            ['name' =>'B.C.A (Bachelor in Computer Application) - Networking'],
            ['name' =>'B.C.A (Bachelor in Computer Application) - Cyber Security'],
            ['name' =>'B. Math. (Bachelor of Mathematics) - Bachelor of Mathematics'],
            ['name' =>'B. Stat. (Bachelor of Statistics) - Bachelor of Statistics'],
            ['name' =>'B. Des. (Bachelor in Design) - Bachelor in Design'],
            ['name' =>'B.F.A (Bachelor in Fine Arts) - Bachelor in Fine Arts'],
            ['name' =>'B.V.A (Bachelor in Visual Arts) - Bachelor in Visual Arts'],
            ['name' =>'B.Cr.A (Bachelor in Creative Arts) - Bachelor in Creative Arts'],
            ['name' =>'B.P.E (Bachelor in Physical Education) - Bachelor in Physical Education'],
            ['name' =>'B.P.A (Bachelor in Performing Arts) - Bachelor in Performing Arts'],
            
        ];
        
        GraduationDegree::insert($data);
    }
}
