<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterDegree;

class MasterCourse extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            ['name' => 'M.Tech. (Masters of Technology) - Computer Science Engineering'],
            ['name' =>  'M.Tech. (Masters of Technology) - Mechanical Engineering'],
            ['name' =>      'M.Tech. (Masters of Technology) - Electrical Engineering'],
            ['name' =>    'M.Tech. (Masters of Technology) - Electronics and Communication and Engineering'],
            ['name' =>      'M.Tech. (Masters of Technology) - Civil Engineering'],
            ['name' => 'M.Tech. (Masters of Technology) - Chemical Engineering'],
            ['name' =>  'M.Tech. (Masters of Technology) - Aerospace Engineering'],
            ['name' =>  'M.Tech. (Masters of Technology) - Biotechnology Engineering'],
            ['name' =>'M.Tech. (Masters of Technology) - Environmental Engineering'],
            ['name' => 'M.Tech. (Masters of Technology) - Artificial Intelligence and Machine Learning'],
            ['name' =>     'M.E (Master of Engineering) - Computer Science Engineering'],
            ['name' =>    'M.E (Master of Engineering) - Mechanical Engineering'],
            ['name' =>    'M.E (Master of Engineering) - Electrical Engineering'],
            ['name' =>    'M.E (Master of Engineering) - Electronics and Communication and Engineering'],
            ['name' =>   'M.E (Master of Engineering) - Civil Engineering'],
            ['name' =>       'M.E (Master of Engineering) - Chemical Engineering'],
            ['name' =>       'M.E (Master of Engineering) - Aerospace Engineering'],
            ['name' =>       'M.E (Master of Engineering) - Biotechnology Engineering'],
            ['name' => 'M.E (Master of Engineering) - Environmental Engineering'],
            ['name' =>    'M.E (Master of Engineering) - Artificial Intelligence and Machine Learning'],
            ['name' =>       'M.Sc. (Master of Science) - Mathematics'],
            ['name' =>        'M.Sc. (Master of Science) - Physics'],
            ['name' =>       'M.Sc. (Master of Science) - Chemistry'],
            ['name' =>         'M.Sc. (Master of Science) - Biology'],
            ['name' =>      'M.Sc. (Master of Science) - Computer Science'],
            ['name' =>    'M.Sc. (Master of Science) - Electronics'],
            ['name' =>      'M.Sc. (Master of Science) - Biotechnology'],
            ['name' =>    'M.Sc. (Master of Science) - Agriculture'],
            ['name' =>       'M.Sc. (Master of Science) - Nursing'],
            ['name' =>       'M.Sc. (Master of Science) - Trauma Care Management'],
            ['name' =>       'M.FTech. (Master of Fashion Technology) - Apparel Production'],
            ['name' =>       'M.FTech. (Master of Fashion Technology) - Fashion Design'],
            ['name' =>      'M.FTech. (Master of Fashion Technology) - Textile Design'],
            ['name' =>           'M.FTech. (Master of Fashion Technology) - Leather Design'],
            ['name' =>          'M.FTech. (Master of Fashion Technology) - Knitwear Desig'],
            ['name' =>       'M. Arch. (Master of Architecture) - Architecture'],
            ['name' =>        'M. Arch. (Master of Architecture) - Interior Design'],
            ['name' =>    'M. Arch. (Master of Architecture) - Landscape Architecture'],
            ['name' =>     'M. Arch. (Master of Architecture) - Building Science'],
            ['name' =>       'M. Plan. (Master of Planning) - Urban Planning'],
            ['name' =>       'M. Plan. (Master of Planning) - Regional Planning'],
            ['name' =>   'M. Plan. (Master of Planning) - Environmental Planning'],
            ['name' =>     'M. Plan. (Master of Planning) - Transportation Planning'],
            ['name' =>      'M. Plan. (Master of Planning) - Infrastructure Planning' ],
            ['name' =>     'M.I.D (Master of Interior Design) - Initerior Design'],
            ['name' =>       'M.I.D (Master of Interior Design) - Furniture Design'],
            ['name' =>    'M.I.D (Master of Interior Design) - Spatial Design'],
            ['name' =>      'M.I.D (Master of Interior Design) - Exhibition Design'],
            ['name' =>       'M. Des. (Master of Design) - Fashion Design'],
            ['name' =>     'M. Des. (Master of Design) - Product Design'],
            ['name' =>     'M. Des. (Master of Design) - Interior Design'],
            ['name' =>      'M. Des. (Master of Design) - Graphic Design'],
            ['name' =>     'M. Des. (Master of Design) - Animation Design'],
            ['name' =>    'Dual Programs in Engineering (B.Tech. + M.Tech) - Electrical Engineering'],
            ['name' =>         'Dual Programs in Engineering (B.Tech. + M.Tech) - Computer Science Engineering'],
            ['name' =>       'Dual Programs in Engineering (B.Tech. + M.Tech) - Mechanical Engineering'],
            ['name' =>         'Dual Programs in Engineering (B.Tech. + M.Tech) - Civil Engineering'],
            ['name' =>          'M.Com. (Master of Commerce) - Accounting and Finance'],
            ['name' =>           'M.Com. (Master of Commerce) - Banking and Insurance'],
            ['name' =>         'M.Com. (Master of Commerce) - Taxation'],
            ['name' =>        'M.Com. (Master of Commerce) - Computer Applications'],
            ['name' =>        'M.Com. (Master of Commerce) - E-Commerce'],
            ['name' =>         'M.Com. (Hons.) (Master of Commerce Honos.) - Accounting and Finance'],
            ['name' =>      'M.Com. (Hons.) (Master of Commerce Honos.) - Banking and Insurance'],
            ['name' =>         'M.Com. (Hons.) (Master of Commerce Honos.) - Taxation'],
            ['name' =>         'M.Com. (Hons.) (Master of Commerce Honos.) - Marketing'],
            ['name' =>       'M.Com. (Hons.) (Master of Commerce Honos.) - Human Resource Management'],
            ['name' =>      'M.D.S (Master of Dental Surgery) - Dental Surgery'],
            ['name' =>           'M.A.M.S (Master of Ayurvedic Medicine & Surgery) - Aryudedic Medicine & Surgery'],
            ['name' =>           'm.S.M.S (Master of Siddha Medicine & Surgery) - Siddha Medicine & Surgery'],
            ['name' =>          'M.N.Y.S (Master of Naturopathy & Yogic Science) - Naturopathy & Yogic Science'],
            ['name' =>        'M.H.M.S (Master of Homeopathic Medicine & Surgery) - Homeopathic Medicine & Surgery'],
            ['name' =>      'M.U.M.S (Master of Unani Medicine & Surgery) - Unani Medicine & Surgery'],
            ['name' =>      'M.Optom. (Master of Optometry) - Optometry'],
            ['name' =>       'M.O.T (Master of Occupational Therapy) - Occupational Therapy'],
            ['name' =>       'M.P.T (Master of Physiotherapy) - Physiotherapy'],
            ['name' =>     'D. Pharma (Doctor of Pharmacy) - Pharmacy'],
            ['name' =>        'M. Pharma (Master of Pharmacy) - Pharmacy'],
            ['name' =>      'M. Pharm (Ayu) (Masterof Pharmacy (Aryuveda)) - Pharmacy (Aryuveda)'],
            ['name' =>       'M.P.O. (Master of Prosthetics & Orthotics) - Prosthetics & Orthotics'],
            ['name' =>       'M. ASLP (Master in Audiology & Speech Language Pathology) - Audiology & Speech Language Pathology'],
            ['name' =>          'M.R. Sc. (Master in Rehabilitation Science) - Rehabilitation Science'],
            ['name' =>        'M.V. Sc. (Master of Veterinary Sciences) - Veterinary Sciences'],
            ['name' =>       'M.F. Sc. (Master of Fisheries Science) - Fisheries Science'],
            ['name' =>       'M.Sc. (Master of Science) - Finance'],
            ['name' =>           'M.Sc. (Master of Science) - Hospitality & Hotel Administration'],
            ['name' =>           'M.Sc. Hons. (Master of Science) - Economics'],
            ['name' =>           'M.B.A (Master of Business Administration) - Finance'],
            ['name' =>           'M.F.A (Master of Financial Accounting) - Financial Accounting'],
            ['name' =>           'M.Com. (Master of Commerce) - Professional'],
            ['name' =>          'M.A (Master in Arts) - English, History, Political Science, Socialogy, Psychology, Economics, Fine Arts - or Language Hindi, Sanskrit, French, German and ,Spanish among other'],
            ['name' =>           'M.A. (Hons) - Hotel Management'],
            ['name' =>            'M.A. (Hons) - Culinary Arts'],
            ['name' =>           'M.A (Master in Arts) - Journalism'],
            ['name' =>           'M.A (Master in Arts) - Communication Media'],
            ['name' =>                'M.A (Master in Arts) - Sports Management'],
            ['name' =>             'C.A (Chartered Accountant) - Chartered Accountant'],
            ['name' =>      'C.S (Company Secretary) - Company Secretary'],
            ['name' =>        'C.W.A (Cost and Works Accountant) - Cost and Works Accountant'],
            ['name' =>        'C.F.A (Certified Finance Analyst) - Certified Finance Analyst'],
            ['name' =>        'C.F.P (Certified Financial Planner) - Certified Financial Planner'],
            ['name' =>       'C.I.B (Certified Investment Banker) - Certified Investment Banker'],
            ['name' =>        'C.S.B (Certified Stock Broker) - Certified Stock Broker'],
            ['name' =>        'C.I.A (Certified Investment Analyst) - Certified Investment Analyst'],
            ['name' =>        'Certified Actuary - Certified Actuary'],
            ['name' =>          'NSE Certifications - NSE Certifications'],
            ['name' =>      'M.S.E Certifications - B.S.E Certifications'],
            ['name' =>         'M.B.A (Master in Business Administration) - General'],
            ['name' =>          'M.B.A (Master in Business Administration) - Marketing'],
            ['name' =>          'M.B.A (Master in Business Administration) - Finance'],
            ['name' =>          'M.B.A (Master in Business Administration) - Human Resources'],
            ['name' =>         'M.B.A (Master in Business Administration) - International Business'],
            ['name' =>        'M.B.A (Master in Business Administration) - Information Technology'],
            ['name' =>         'M.B.A (Master in Business Administration) - Entrepreneurship'],
            ['name' =>           'M.B.A (Master in Business Administration) - Operations Management'],
            ['name' =>         'M.B.A (Master in Business Administration) - Sports Management'],
            ['name' =>          'M.Sc. LLB (Master In Science & Bachelor in Law) - Bachelor in Law'],
            ['name' =>         'M.A LLB (Master in Arts & Bachelor in Law) - B.sc with Bachelor in Law'],
            ['name' =>         'M.Com LLB (Master in Commerce & Master in Law) - B.Com with Bachelor in Law'],
            ['name' =>        'M.B.A LLB (Master in Business Administration & Master in Law) - B.B.A Bachelor in Law'],
            ['name' =>         'M.L.S LLB (Master in Liberal Arts & Master in Law) - B.L.S Bachelor in Law'],
            ['name' =>         'M.S.W LLB (Master in Social Work & Master in Law) - B.S.W Bachelor in Law'],
            ['name' =>            'M. Tech LLB (Master in Technology & Master in Law) - B.Tech with Bachelor in Law'],
            ['name' =>         'M.M.S (Master in Management Studies) - Bachelor in Management Studies'],
            ['name' =>         'M.B.S (Master in Business Studies) - Bachelor in Business Studies'],
            ['name' =>          'M.B.M (Master in Business Management) - Bachelor in Business Management'],
            ['name' =>         'M.Tech (Master of Technology) - Hotel Management & Catering Technology'],
            ['name' =>            'M.M.M (Master in Mass Media) - Bachelor in Mass Media'],
            ['name' =>              'M.M.C (Master in Mass Communication) - Bachelor in Mass Communication'],
            ['name' =>         'M.M.S (Master in Media Studies) - Bachelor in Media Studies'],
            ['name' =>          'M.J.M.C (Master in Journalism & Mass Communication) - Bachelor in Journalism & Mass Communication'],
            ['name' =>         'M.S.W (Master in Social Work) - Bachelor in Social Work'],
            ['name' =>         'M.R.S (Master in Rural Studies) - Bachelor in Rural Studies'],
            ['name' =>        'M.C.A (Master in Computer Application) - General'],
            ['name' =>        'M.C.A (Master in Computer Application) - Database Management'],
            ['name' =>         'M.C.A (Master in Computer Application) - Web Development'],
            ['name' =>        'M.C.A (Master in Computer Application) - Software Development'],
            ['name' =>          'M.C.A (Master in Computer Application) - Networking'],
            ['name' =>          'M.C.A (Master in Computer Application) - Cyber Security'],
            ['name' =>         'M. Math. (Master of Mathematics) - Bachelor of Mathematics'],
            ['name' =>            'M. Stat. (Master of Statistics) - Bachelor of Statistics'],
            ['name' =>             'M. Des. (Master in Design) - Bachelor in Design'],
            ['name' =>           'M.F.A (Master in Fine Arts) - Bachelor in Fine Arts'],
            ['name' =>          'M.V.A (Master in Visual Arts) - Bachelor in Visual Arts'],
            ['name' =>          'M.Cr.A (Master in Creative Arts) - Bachelor in Creative Arts'],
            ['name' =>          'M.P.E (Master in Physical Education) - Bachelor in Physical Education'],
            ['name' =>          'M.P.A (Master in Performing Arts) - Bachelor in Performing Arts'],
                
        ];

        MasterDegree::insert($data);
    }
}
